FROM ubuntu:22.04

ARG APP_UID=17163
ARG APP_GID=10000

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:1

# Fix GPG keys and update package lists
RUN rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    apt-get update --allow-releaseinfo-change && \
    apt-get install -y --no-install-recommends \
    build-essential \
    xvfb \
    libxpm4 \
    libxpm-dev \
    libx11-dev \
    libxt-dev \
    libxm4 \
    openssl \
    ca-certificates \
    && groupadd -g $APP_GID appgroup \
    && useradd -m -u $APP_UID -g $APP_GID appuser \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD assets/ptools/aic-export-30.0.tar.gz /app/
RUN mkdir -p /app/ptools && \
    ./aic-export/pathway-tools/ptools/30.0/install/config-ptools /app/ptools

VOLUME ["/app/scratch"]
ENV SERVER_HOST_NAME=ptools.sms-api-eks.svc.cluster.local

EXPOSE 1555
EXPOSE 5008
#
CMD bash -c "\
    Xvfb :1 -screen 0 1024x768x16 & \
    sleep 2 && \
    /app/pathway-tools -www -www-server-hostname ${SERVER_HOST_NAME} -port 1555 -python"
