apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viva-core-projects-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1000Gi
  volumeName: viva-core-projects-pv
