---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workbench-gh-token
  namespace: sms-api-stanford
spec:
  encryptedData:
    VIVARIUM_WORKBENCH_GH_TOKEN: AgBmbeasQCrm4ezOj2PrnGFl5k4s69p27r3nRGxfxIPVBjVZ3u8xppGIz5vSZLhBcXLtO2PrYwGS/IG2Ku29zuT+hRi1cEUS6XeX1DfRq0qcQkfka7gS7F1db4QI6Y2vq3zmbSRLULfhicFhvMMVfYYMK+1RCi6ZtPzH5m/UEOJrQyznc1gC+zSlGujE/XtgEZrSV1umD+W8FysCnA9sBdcH165Bhapov1Md+K4DMrGgnYIwdnWFvbUS1wWL/ygD6Zq8VMWFx9buaFkPXXtqNRya89wMab04AkR+63nunQSyK3b5fOuNrDhkTYPAnlXNq8BLiOD9aTjdP0XySQMc63YpF01YVHNoPf5Nv2+pAHpAielbwpXnHsmcsQXhXICyJsOytPjV1carPSzSFU07ShiSxfTDGqqf0tB4oZ2Jb78aNhJVzWNAhwm0WlPwXzMPrhGHtlWMA2u49liUjIIa6WtTavMl8ad+9vJYaMWLNJxD8WqNKlI1sPEG13xphF+BmE2ncbdOsj9dWj/7z2gKjpKmsiLlTakDp/Mm1z0bw4yJ1OM/aaYfIOdWXFx0z96MJIa6M1ATR+pME8McQH8KtSyZOESDwrzzxevg9u0vfjlfFIp9nvwUgb9d7DW3ptb38Bdsq/JgcLPDtoL/cqNRCcrxDXQ5PcXVxaBvTIQlApNe3c+8+9u0ui68wFyJvfGcC88KXkT1sSuvwVLMxZwgG5ZTWvWNzpC1lfDN92zW6aRCvBeswJDvkylrfQZdpjmTu4OAePbL1iA4yf6AVOZ1dKo+LZG4rKuMf9WavLUKICbfcvg9lGC3GfesU4+64gU=
  template:
    metadata:
      creationTimestamp: null
      name: workbench-gh-token
      namespace: sms-api-stanford
