---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: sms-api-stanford
spec:
  encryptedData:
    .dockerconfigjson: AgCeHm+3E2gYjYFIrglfUH27P1hoB2BDLpNnRG+palJRmj9SgLF0+68e2407FHdjXm/Cz7rTqJCTLp07NlMWVQnyu8Mg/NE5g0b3ZRAVh4Iw6cVFyti10pWKmPciZmZIlhBlyeQn6VK+AbzOXBM2F17cd6CmFWsWHz1up+Lr+5/qVqBJRGSExsQojnwi54yjiyHV9AJzEbMd5XIzZJzmf50jzD9Wh/LNKgMF2KfjYXPg5n/3wZ3YBn8net2UWGlrbVpQN97AKevfycPu7pQmLQVGBsIoW8TI69txSFRKEyzkygKbrheBqJggD1//hZPIYJmmID/cKyMobAbhiJ4fL3WkcRe33HAN+J8EbZFqLa071Dl0H4bheBSQCAV6wEO7VagcN8XGRWFeSfHBlJrOlF1fBiWFsVNyQ7B1PogXGdIU+tNGbhpewq2I+HvzkDzHUJH9NSC5576Omt4jgSJiaKx6k0+NiNAYlqeJR04SeOX5liOu4e4zKBTU1jef6lYMiTg67UNyBsSWXPhdMIQaZ8/QeHd6ccvsnnxGWmhrAg6AdPxAlkhcSyvcyiEdoVX9BcZBgsJPl7a92CLB36HglndELGojupvSiMdPJvnqLeHLNppHVq5HwFq9tiXrTipiXxbwsmXhTHfiP4jOxfI9jopLrTZ/omVOmrvuM3oaI3QCSRA1xV4giaa0qGFYlUjQL28TLLmagEGN3bxVackpkE3LN6Lh3w2Hgs6v2EFwendCROLSaGwMHF9EQzNxrjMGiN0esIH78fdCFT6YP3FHV3HS4iYzEBDeVQfL5VHmT1XsmFpDT5/St5yZCqxGxOob1D8kMErHdKmOuNF45W70ny4/RhKtWf6g46b1WL9QTk2tSfDV/OQamTpGAAd8maN4iTDQ00f6cbNVfDiQB6jQpUXdQ3PZg9GqBAvUI+OKOEAlcGL8gtMxMJLNxi8x1Zk7UA0kT4LeQbayYLqWhw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: sms-api-stanford
    type: kubernetes.io/dockerconfigjson
