---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workbench-gh-token
  namespace: sms-api-stanford
spec:
  encryptedData:
    VIVARIUM_WORKBENCH_GH_TOKEN: AgC2TwTGOhm/FzMRbGmxqpniiFvEkHwjznCwYiwjZzbWd+pvGKuz6CARWUzUb8JscLMostgQwZZVJMYsptTfdMuf2ENRY3WFTXdSGh1WEinrmVWFvAWgkXBREum0Cswf9H2NdQwaYt1VLEnV3b/2yKdsjrSv6wELvDapXvF0K/vlSblfMa3ysDV30Fjx8ZJOp1VQtkRjDMAvYWL/yrKzaAkMKEreyK0/NPvjQfD8q/LDfcoZPDQoF2vrtSPudbYFtxk2GVaN87YQYXZ0y9eoMNOX8yLbs6w/KdMCq3QwdQIJO6X9HQXX/9hc2JXYedPgkX6dVtpRYDGuxHg7dwHg3fr6Y2rSfylw3xBSV/RSLtPLjLFPe1Sk/5DARfFH6rBbssnVJ3wK3NzfWotfsTJ3J39FCLKuqg/LePxhsT/2lo5TDVzHpDuFV52DfEgWi0mny4xiZptMXsJOdKR9S3v7f8IrO0KWX2IdUOsWjb5601tQMdyX222L5QH0CaZds/oKfZ4L9YlOaNYBqHvVK4mZrQbsD1wCq8oXpiAupBiKuETGS9a2Po1G5EmOdOOAnbhHtjXiGzdPBxNnp888eEx4+I4dLIpXHQt4mMNs6AQznOJqrz4rY5l5QP0PoShRYZv8EePwT6fro5kmN+0wSedudOZ1CrvXesIVDqzuTgbcKgPG1pKkiierAMjoEtf53DJPOoKQ5O2UuwI1GZH/azxsapvvIB3hD3qzvG85F/C0O4Ya8g4SQoiX9o32oOOvQQISfOUrwWPq9Thu1Qeo7A0qOxFiIgXt6GU08uRgQUW9SVvsS3ecxcqHaaICyJZwaDo=
  template:
    metadata:
      creationTimestamp: null
      name: workbench-gh-token
      namespace: sms-api-stanford
    type: Opaque
